version: 2.1

workflows:
  clojure:
    jobs:
      - shared__clj-lint:
          name: clojure__clj-lint__<<matrix.alias>>
          matrix:
            parameters:
              alias:
                - cljfmt/check
                - clj-kondo .
                - splint
          project: clojure
      - shared__antq:
          name: clojure__antq
          project: clojure
